baseURL = "/"
languageCode = "en-us"
title = "Leafee's Blog"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 6 # Set the number of posts to show before overflowing to the next page.
summaryLength = 1 # Configure how long the post summary should be on the homepage.

[taxonomies]
	tag = "tags"

[author]
	name = "Leafee"

[params]
	math = true
	description = "Blog of Leafee, or called note of Leafee better."
	email = "leafee98@hotmail.com"
	twitter = "twitter.com/leafee98"
	github = "github.com/leafee98"

[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2

[[menu.main]]
	identifier = "archives"
	name = "Archives"
	url = "/archives/"
	weight = 3

[[menu.main]]
	identifier = "essay"
	name = "Essay"
	url = "/essay/"
	weight = 4

